kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-role
rules:
- apiGroups:
  - triggers.tekton.dev
  resources:
  - eventlisteners
  - triggerbindings
  - triggertemplates
  - pipelineresources
  verbs:
  - get
- apiGroups:
  - ""
  # secrets are only needed for Github/Gitlab interceptors, serviceaccounts only for per trigger authorization
  resources:
  - secrets
  - configmaps
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelineresources
  verbs:
  - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-rolebinding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-role
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: quizz-client-pipeline-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
  - template:
      name: quizz-client-pipeline-triggertemplate
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: quizz-client-pipeline-listener
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-quizz-client-pipeline-listener
    weight: 100